import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>First Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{' '}
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />
            
            </a>
          </div>
        </div>

        
        <div className={styles.center}>
        <h1>👋 Hi there! I'm Masab Bin Zia, a Junior Frontend Developer and Computer Science student.</h1>
        </div>

        <div className={styles.grid}>
          <a
            href="https://github.com/MasabBinZia"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Github <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Check out My Github for more info.
            </p>
          </a>
          <a
            href="https://www.youtube.com/@masabbinzia6523"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Youtube <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Check out My Youtube for more info.
            </p>
          </a>
          <a
            href="https://twitter.com/hadescreeping"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
            Twitter <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              DM me on My Twitter for any questions.
            </p>
          </a>
        </div>
      </main>
    </>
  )
}
